[package]
name = "mouse_rust_assistant"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "0.2.8"
mouse-rs = "0.4.1"
stopwatch = "0.0.7"
ctrlc = "3.2.0"